# Example Secret: Curity Identity Server license file.
# The operator mounts this to /opt/idsvr/etc/init/license/license.json
# because curity.io/config-type is "license".
# Obtain the license file from https://developer.curity.io/
---
apiVersion: v1
kind: Secret
metadata:
  name: curity-license
  namespace: curity
  labels:
    curity.io/managed: "true"
  annotations:
    curity.io/config-type: "license"
type: Opaque
stringData:
  license.json: |
    <paste license.json content here>
