name: Pull Request

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
      - 'docs/'

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Generate Manifests
        run: make manifests generate

      - name: Lint
        run: make lint

      - name: Unit Tests
        run: make test

      - name: Build
        run: make build

      - name: Docker Build
        run: make docker-build

      - name: Generate Helm Chart
        run: make helmify

      - name: Helm Lint
        run: helm lint charts/curity-operator --strict
